const weatherData = {
    'chattanooga': {
        location: 'Chattanooga, TN',
        currentTemp: 71,
        feelsLike: 71,
        highTemp: 79,
        lowTemp: 57,
        conditions: "Partly Cloudy",
        humidity: 61,
        wind: 3,
    },
    'saint louis': {
        location: 'Saint Louis, MO',
        currentTemp: 65,
        feelsLike: 65,
        highTemp: 78,
        lowTemp: 50,
        conditions: "Clear",
        humidity: 50,
        wind: 1,
    },
    'kansas city': {
		location: 'Kansas City, MO',
		currentTemp: 76,
		feelsLike: 76,
		highTemp: 76,
		lowTemp: 63,
		conditions: 'Sunny',
		humidity: 41,
		wind: 13,
	},
	philadelphia: {
		location: 'Philadelphia, PA',
		currentTemp: 74,
		feelsLike: 74,
		highTemp: 75,
		lowTemp: 54,
		conditions: 'Sunny',
		humidity: 33,
		wind: 7,
	},
    tampa: {
		location: 'Tampa, FL',
		currentTemp: 84,
		feelsLike: 94,
		highTemp: 87,
		lowTemp: 75,
		conditions: 'Mostly Cloudy',
		humidity: 80,
		wind: 3,
	},
	fairbanks: {
		location: 'Fairbanks, AK',
		currentTemp: 59,
		feelsLike: 59,
		highTemp: 60,
		lowTemp: 44,
		conditions: 'Cloudy',
		humidity: 68,
		wind: 4,
	},
	phoenix: {
		location: 'Phoenix, AZ',
		currentTemp: 104,
		feelsLike: 108,
		highTemp: 105,
		lowTemp: 85,
		conditions: 'Partly Cloudy',
		humidity: 25,
		wind: 8,
	},
};

export default weatherData;